// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuthed() {
  return window['go']['main']['App']['CheckAuthed']();
}

export function Launch(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Launch'](arg1, arg2, arg3, arg4, arg5);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MirrorLog(arg1) {
  return window['go']['main']['App']['MirrorLog'](arg1);
}
