// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {websocket} from '../models';

export function CheckAuthed():Promise<boolean>;

export function Launch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function Logout():Promise<void>;

export function MirrorLog(arg1:websocket.Conn):Promise<void>;
